# wszystko z małych liter
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update #tworzy automatycznie pola i tabelki, usówać trzeba już ręcznie
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    baseline-on-migrate: true #inicjalizuje historie flywaya gdy schemat bazodanowy nie jest pusty
  mail:
    host: smtp.gmail.com
    port: 587
    username: konto.testowe.dev.java
    password: admin.dev123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
file:
  product: C:\Users\andre\Pictures\Java
